// Package heal runs before every rebuild, sequencing gitignore, framework,
// imports, generate, links, units, refs, computer, staging, userfile, and
// printing progress to the given io.Writer. No parsing or decision logic:
// each package takes explicit directories, returns values plus error.
package heal

import (
	"errors"
	"fmt"
	"io"
	"path/filepath"
	"strings"

	"github.com/DeprecatedLuar/luxos/internal/computer"
	"github.com/DeprecatedLuar/luxos/internal/config"
	"github.com/DeprecatedLuar/luxos/internal/framework"
	"github.com/DeprecatedLuar/luxos/internal/generate"
	"github.com/DeprecatedLuar/luxos/internal/gitignore"
	"github.com/DeprecatedLuar/luxos/internal/imports"
	"github.com/DeprecatedLuar/luxos/internal/links"
	"github.com/DeprecatedLuar/luxos/internal/nix"
	"github.com/DeprecatedLuar/luxos/internal/paths"
	"github.com/DeprecatedLuar/luxos/internal/refs"
	"github.com/DeprecatedLuar/luxos/internal/staging"
	"github.com/DeprecatedLuar/luxos/internal/templates"
	"github.com/DeprecatedLuar/luxos/internal/units"
	"github.com/DeprecatedLuar/luxos/internal/userfile"
)

var gitignoreLines = []string{"/modules/default.nix", "/modules/system", "/modules/local", "/local", "/.local/machines/*/modules/hardware-support"}

// Nix invocations, replaceable so tests need neither network nor flake-file.
var (
	writeFlake = nix.WriteFlake
	flakeLock  = nix.FlakeLock
)

const selectionFile = "modules.nix"

const (
	environmentFile     = "environment"
	environmentTemplate = "starters/environment"

	machineTemplate  = "starters/machine.nix"
	hardwareTemplate = "starters/hardware.nix"

	hardwareDefaultTemplate = "starters/hardware-default.nix"

	hardwareConfigNote = " (generated by nixos-generate-config; luxos never rewrites it)"
	bootNote           = " (review it; luxos never rewrites it)"
)

// progress prints to w and keeps the first write error, so a broken output
// stream is reported rather than dropped while Run keeps sequencing.
type progress struct {
	w   io.Writer
	err error
}

func (o *progress) printf(format string, a ...any) {
	if o.err == nil {
		_, o.err = fmt.Fprintf(o.w, format, a...)
	}
}

func ensureMachineFile(out *progress, hostDir string) error {
	tmpl, err := templates.File(machineTemplate)
	if err != nil {
		return err
	}
	path := filepath.Join(hostDir, config.MachineFile)
	created, err := userfile.Create(path, tmpl)
	if err != nil {
		return err
	}
	if created {
		out.printf("  created: %s\n", path)
	}
	return nil
}

func ensureHardware(out *progress, p paths.Paths) (string, error) {
	key, err := computer.HardwareKey(p.Sys)
	if err != nil {
		return "", err
	}
	hwDir := filepath.Join(p.HardwareRoot, key)
	out.printf("Ensuring %s...\n", hwDir)
	if err := userfile.MkdirAll(hwDir); err != nil {
		return "", err
	}

	hwConfig := filepath.Join(hwDir, config.HardwareConfigFile)
	created, err := computer.EnsureHardwareConfig(hwConfig)
	if err != nil {
		return "", err
	}
	if created {
		out.printf("  created: %s%s\n", hwConfig, hardwareConfigNote)
	}

	bootPath := filepath.Join(hwDir, config.BootFile)
	created, err = computer.EnsureBoot(bootPath, p.Sys, p.Mounts)
	if err != nil {
		return "", err
	}
	if created {
		out.printf("  created: %s%s\n", bootPath, bootNote)
	}

	tmpl, err := templates.File(hardwareTemplate)
	if err != nil {
		return "", err
	}
	hwPath := filepath.Join(hwDir, config.HardwareFile)
	created, err = userfile.Create(hwPath, tmpl)
	if err != nil {
		return "", err
	}
	if created {
		out.printf("  created: %s\n", hwPath)
	}

	defaultTmpl, err := templates.File(hardwareDefaultTemplate)
	if err != nil {
		return "", err
	}
	defaultPath := filepath.Join(hwDir, config.DefaultFile)
	created, err = userfile.Create(defaultPath, defaultTmpl)
	if err != nil {
		return "", err
	}
	if created {
		out.printf("  created: %s\n", defaultPath)
	}

	if err := config.ValidateHardware(hwDir); err != nil {
		return "", err
	}
	return hwDir, nil
}

func selectedInputsNix(modulesDir, hostDir string) (string, error) {
	sel, err := refs.SelectedUnits(modulesDir, filepath.Join(hostDir, "modules"), hostDir)
	if err != nil {
		return "", err
	}
	files := []string{filepath.Join(hostDir, config.MachineFile)}
	for _, u := range sel {
		files = append(files, u.Files...)
	}
	decls, err := nix.InputDecls(files...)
	if err != nil {
		return "", err
	}
	return nix.RenderInputs(decls), nil
}

func readBaseChannel(path string) (string, error) {
	url, _, err := nix.BaseChannel(path)
	if errors.Is(err, nix.ErrNoBaseChannel) {
		return "", fmt.Errorf("%s: %w\n  add: %s", path, err, baseChannelHint())
	}
	return url, err
}

func baseChannelHint() string {
	tmpl, err := templates.File(machineTemplate)
	if err == nil {
		for _, line := range strings.Split(string(tmpl), "\n") {
			if strings.Contains(line, nix.BaseChannelInput+".url") {
				return strings.TrimSpace(line)
			}
		}
	}
	return "flake-file.inputs.nixpkgs.url = \"<flake url>\";"
}

// checkMachineFile fails when the machine.nix at path holds any static or
// dynamic path literal.
func checkMachineFile(path string) error {
	static, err := nix.Paths(path)
	if err != nil {
		return err
	}
	dynamic, err := nix.DynamicPaths(path)
	if err != nil {
		return err
	}
	offenders := append(static, dynamic...)
	if len(offenders) == 0 {
		return nil
	}
	return fmt.Errorf("%s holds path literals or imports: %s\n"+
		"paths in machine.nix resolve against the staged copy at /etc/nixos/config/, not the host folder, "+
		"and module selection belongs in modules.nix; add a module with:\n  luxos module enable <name>",
		path, strings.Join(offenders, ", "))
}

// Run performs the full self-heal sequence for host: ensure .gitignore,
// ensure global environment file, sync framework modules, validate and protect
// the host folder, ensure this computer's hardware folder and the host's link
// to it, heal host entrypoints, validate module boundaries, adopt /etc/nixos,
// materialize staging, generate+install framework/flake-file.nix, detect GPUs
// and install framework/gpu.nix, then flake.nix via flake-file, and
// framework/configuration.nix. prune, when true, removes unresolvable import
// lines from the active host's entrypoint instead of erroring.
func Run(w io.Writer, p paths.Paths, host string, prune bool) error {
	hostDir := filepath.Join(p.Machines, host)
	out := &progress{w: w}

	// 1. gitignore
	out.printf("Ensuring .gitignore...\n")
	added, err := gitignore.Ensure(filepath.Join(p.Config, ".gitignore"), gitignoreLines)
	if err != nil {
		return err
	}
	for _, line := range added {
		out.printf("  added: %s\n", line)
	}

	// 1b. environment file
	out.printf("Ensuring environment file...\n")
	tmpl, err := templates.File(environmentTemplate)
	if err != nil {
		return err
	}
	envPath := filepath.Join(p.Config, environmentFile)
	created, err := userfile.Create(envPath, tmpl)
	if err != nil {
		return err
	}
	if created {
		out.printf("  created: %s\n", envPath)
	}

	// 2. framework modules sync
	out.printf("Syncing framework modules...\n")
	changes, err := framework.Sync(filepath.Join(p.Modules, "system"))
	if err != nil {
		return err
	}
	for _, c := range changes {
		line := fmt.Sprintf("%s: %s", c.Action, c.Path)
		if c.Action == framework.ActionCreated {
			out.printf("%s\n", line)
		} else {
			out.printf("Warning: %s\n", line)
		}
	}

	// 2b. machine.nix from the template when missing
	if err := ensureMachineFile(out, hostDir); err != nil {
		return err
	}

	// 3. validate and protect the host folder
	out.printf("Validating %s...\n", hostDir)
	if err := config.ValidateHost(hostDir); err != nil {
		return err
	}
	protected, err := config.ProtectHost(hostDir)
	if err != nil {
		return err
	}
	if protected {
		out.printf("  protected: %s\n", filepath.Join(hostDir, ".plsdonttouch.nix"))
	}

	// 3b. this computer's hardware folder, then the link to it
	hwDir, err := ensureHardware(out, p)
	if err != nil {
		return err
	}
	key := filepath.Base(hwDir)
	out.printf("Ensuring local/modules/hardware-support -> .local/hardware/%s link...\n", key)
	if err := links.EnsureHardwareLink(p.Machines, p.HardwareRoot, host, key); err != nil {
		return err
	}

	// 4. ensure modules mirror
	out.printf("Ensuring %s's modules mirror...\n", host)
	if err := links.EnsureMirror(p.Machines, p.Modules, host); err != nil {
		return err
	}

	// 4b. ensure modules/local -> .local/machines/<host>/modules link
	out.printf("Ensuring modules/local -> .local/machines/%s/modules link...\n", host)
	if err := links.EnsureLocalModules(p.Machines, p.Modules, host); err != nil {
		return err
	}

	// 5. heal imports
	out.printf("Healing modules imports...\n")
	healChanges, healWarnings, err := imports.Heal(p.Machines, p.Modules, host, prune)
	for _, c := range healChanges {
		out.printf("%s\n", formatImportChange(c))
	}
	for _, wm := range healWarnings {
		out.printf("Warning: %s\n", wm)
	}
	if err != nil {
		return err
	}

	// 6. validate module boundaries
	out.printf("Validating module boundaries...\n")
	us, err := units.Walk(p.Modules, filepath.Join(hostDir, "modules"))
	if err != nil {
		return err
	}
	selection, err := imports.List(filepath.Join(hostDir, selectionFile))
	if err != nil {
		return err
	}
	violations, err := refs.Validate(p.Modules, us, selection)
	if err != nil {
		return err
	}
	if len(violations) > 0 {
		for _, v := range violations {
			out.printf("Error: %s: %s\n", v.File, v.Message)
		}
		return fmt.Errorf("module boundary violations: %d", len(violations))
	}

	// 6b. machine.nix may hold no path literals and no imports
	if err := checkMachineFile(filepath.Join(hostDir, config.MachineFile)); err != nil {
		return err
	}

	// 6c. the base channel is declared in machine.nix
	if _, err := readBaseChannel(filepath.Join(hostDir, config.MachineFile)); err != nil {
		return err
	}

	// 7. ensure local link
	out.printf("Ensuring local -> .local/machines/%s link...\n", host)
	if err := links.EnsureLocalLink(p.Config, p.Machines, host); err != nil {
		return err
	}

	// 7a. adopt the flake root: move strangers out of it
	out.printf("Adopting %s...\n", p.Staging)
	adoptChanges, err := staging.Adopt(p.Staging, p.Backup)
	if errors.Is(err, staging.ErrNoBackupDir) {
		return fmt.Errorf("%s holds entries luxos does not own and there is no user to move them to; choose a directory with:\n  luxos rebuild --backup-dir <path>", p.Staging)
	}
	if err != nil {
		return err
	}
	for _, c := range adoptChanges {
		if c.Kind == staging.ChangeMoved {
			out.printf("  moved: %s -> %s\n", c.Path, c.Dest)
		} else {
			out.printf("  converted %s from a symlink to a real directory\n", c.Path)
		}
	}

	// derive the bootstrap flake's inputs from the selected modules' own
	// flake-file.inputs declarations (plus machine.nix's base channel), so a
	// module that imports from its own input (a nixos-hardware module, say)
	// already has that input by the time write-flake evaluates it.
	inputsNix, err := selectedInputsNix(p.Modules, hostDir)
	if err != nil {
		return err
	}

	// 8. materialize staging
	out.printf("Materializing %s for %s...\n", p.Staging, host)
	if err := staging.Materialize(p.Staging, p.Modules, hostDir, us, filepath.Join(hostDir, "flake.lock"), envPath, inputsNix); err != nil {
		return err
	}

	// 9. generate framework/flake-file.nix, let flake-file write flake.nix, lock
	out.printf("Generating flake.nix with flake-file...\n")
	bootstrap, err := generate.FlakeBootstrap(host)
	if err != nil {
		return err
	}
	if err := staging.Install(p.Staging, "framework/flake-file.nix", bootstrap); err != nil {
		return err
	}

	// 9b. detect GPUs and install the fact file
	out.printf("Detecting GPUs...\n")
	gpus, err := computer.DetectGPUs(p.Sys)
	if err != nil {
		return err
	}
	for _, g := range gpus {
		out.printf("  %s %s: %s\n", g.Vendor, g.Class, g.BusID)
	}
	gpuContent, err := computer.RenderGPUs(gpus)
	if err != nil {
		return err
	}
	if err := staging.Install(p.Staging, "framework/gpu.nix", gpuContent); err != nil {
		return err
	}

	if err := writeFlake(p.Staging); err != nil {
		return err
	}
	if err := flakeLock(p.Staging); err != nil {
		return err
	}
	hostLock := filepath.Join(hostDir, "flake.lock")
	changed, err := staging.LockChanged(p.Staging, hostLock)
	if err != nil {
		return err
	}
	if changed {
		if err := staging.CopyLockBack(p.Staging, hostLock); err != nil {
			return err
		}
		out.printf("  locked new inputs: %s\n", hostLock)
	}

	// 10. generate and install framework/configuration.nix
	out.printf("Generating configuration.nix...\n")
	configContent, err := generate.Configuration(host)
	if err != nil {
		return err
	}
	if err := staging.Install(p.Staging, "framework/configuration.nix", configContent); err != nil {
		return err
	}

	// 11. make the generated tree read-only
	out.printf("Sealing %s...\n", p.Staging)
	return errors.Join(staging.Seal(p.Staging), out.err)
}

func formatImportChange(c imports.Change) string {
	if c.New == "" {
		return fmt.Sprintf("%s: removed ./%s", c.File, c.Old)
	}
	return fmt.Sprintf("%s: ./%s -> ./%s", c.File, c.Old, c.New)
}
