// Package heal is the self-healing orchestrator run before every rebuild.
// It sequences internal/gitignore, internal/framework, internal/imports,
// internal/generate, internal/links, internal/units, internal/refs,
// internal/computer, internal/staging and internal/userfile in the fixed
// order the bash self-heal.sh used, printing progress to the given
// io.Writer. It has no parsing or decision logic of its own
// (implementation-plan.md G10/G11): every package it calls takes explicit
// directories and returns values plus error; this file only sequences and
// reports.
package heal

import (
	"errors"
	"fmt"
	"io"
	"path/filepath"
	"strings"

	"github.com/DeprecatedLuar/luxos/internal/computer"
	"github.com/DeprecatedLuar/luxos/internal/config"
	"github.com/DeprecatedLuar/luxos/internal/framework"
	"github.com/DeprecatedLuar/luxos/internal/generate"
	"github.com/DeprecatedLuar/luxos/internal/gitignore"
	"github.com/DeprecatedLuar/luxos/internal/imports"
	"github.com/DeprecatedLuar/luxos/internal/links"
	"github.com/DeprecatedLuar/luxos/internal/nix"
	"github.com/DeprecatedLuar/luxos/internal/nixsrc"
	"github.com/DeprecatedLuar/luxos/internal/paths"
	"github.com/DeprecatedLuar/luxos/internal/refs"
	"github.com/DeprecatedLuar/luxos/internal/staging"
	"github.com/DeprecatedLuar/luxos/internal/units"
	"github.com/DeprecatedLuar/luxos/internal/userfile"
)

// gitignoreLines are the lines CONFIG_DIR's root .gitignore must contain;
// gitignore.Ensure appends whichever are missing and never removes or
// reorders anything else in the file.
var gitignoreLines = []string{"/modules/default.nix", "/modules/system", "/modules/local", "/local", "/.local/machines/*/modules/hardware-support"}

// Nix invocations, replaceable so tests need neither network nor a
// working flake-file.
var (
	writeFlake = nix.WriteFlake
	flakeLock  = nix.FlakeLock
)

// selectionFile is a host's selection file, holding the "imports = [...]"
// block imports.Heal/List read and write (L4).
const selectionFile = "modules.nix"

const (
	// environmentFile is the global environment file at the config root;
	// environmentTemplate is the embedded template written when it is missing.
	environmentFile     = "environment"
	environmentTemplate = "templates/environment"

	// machineTemplate is the embedded template written as the active host's
	// machine.nix when that file is missing; hardwareTemplate likewise for
	// the computer's hardware.nix.
	machineTemplate  = "templates/machine.nix"
	hardwareTemplate = "templates/hardware.nix"

	// hardwareDefaultTemplate is written as the hardware folder's default.nix
	// when that file is missing.
	hardwareDefaultTemplate = "templates/hardware-default.nix"

	// Suffixes of the "created:" lines for the two generated hardware files.
	hardwareConfigNote = " (generated by nixos-generate-config; luxos never rewrites it)"
	bootNote           = " (review it; luxos never rewrites it)"
)

// ensureMachineFile writes the embedded machine.nix template into hostDir
// when nothing is there, and prints one line naming the created path. An
// existing entry, including a symlink, is left alone silently.
func ensureMachineFile(w io.Writer, hostDir string) error {
	tmpl, err := framework.File(machineTemplate)
	if err != nil {
		return err
	}
	path := filepath.Join(hostDir, config.MachineFile)
	created, err := userfile.Create(path, tmpl)
	if err != nil {
		return err
	}
	if created {
		fmt.Fprintf(w, "  created: %s\n", path)
	}
	return nil
}

// ensureHardware creates the hardware folder for this computer under
// p.HardwareRoot and the files missing from it, validates the folder and
// returns its path. The folder is named by computer.HardwareKey.
func ensureHardware(w io.Writer, p paths.Paths) (string, error) {
	key, err := computer.HardwareKey(p.Sys)
	if err != nil {
		return "", err
	}
	hwDir := filepath.Join(p.HardwareRoot, key)
	fmt.Fprintf(w, "Ensuring %s...\n", hwDir)
	if err := userfile.MkdirAll(hwDir); err != nil {
		return "", err
	}

	hwConfig := filepath.Join(hwDir, config.HardwareConfigFile)
	created, err := computer.EnsureHardwareConfig(hwConfig)
	if err != nil {
		return "", err
	}
	if created {
		fmt.Fprintf(w, "  created: %s%s\n", hwConfig, hardwareConfigNote)
	}

	bootPath := filepath.Join(hwDir, config.BootFile)
	created, err = computer.EnsureBoot(bootPath, p.Sys, p.Mounts)
	if err != nil {
		return "", err
	}
	if created {
		fmt.Fprintf(w, "  created: %s%s\n", bootPath, bootNote)
	}

	tmpl, err := framework.File(hardwareTemplate)
	if err != nil {
		return "", err
	}
	hwPath := filepath.Join(hwDir, config.HardwareFile)
	created, err = userfile.Create(hwPath, tmpl)
	if err != nil {
		return "", err
	}
	if created {
		fmt.Fprintf(w, "  created: %s\n", hwPath)
	}

	defaultTmpl, err := framework.File(hardwareDefaultTemplate)
	if err != nil {
		return "", err
	}
	defaultPath := filepath.Join(hwDir, config.DefaultFile)
	created, err = userfile.Create(defaultPath, defaultTmpl)
	if err != nil {
		return "", err
	}
	if created {
		fmt.Fprintf(w, "  created: %s\n", defaultPath)
	}

	if err := config.ValidateHardware(hwDir); err != nil {
		return "", err
	}
	return hwDir, nil
}

// readBaseChannel returns the url of the nixpkgs declaration in the machine.nix
// at path. A missing declaration is an error naming the line to add, taken from
// the embedded machine.nix template.
func readBaseChannel(path string) (string, error) {
	url, _, err := nixsrc.BaseChannel(path)
	if errors.Is(err, nixsrc.ErrNoBaseChannel) {
		return "", fmt.Errorf("%s: %w\n  add: %s", path, err, baseChannelHint())
	}
	return url, err
}

// baseChannelHint is the base-channel line of the embedded machine.nix
// template, or a placeholder form when the template has none.
func baseChannelHint() string {
	tmpl, err := framework.File(machineTemplate)
	if err == nil {
		for _, line := range strings.Split(string(tmpl), "\n") {
			if strings.Contains(line, nixsrc.BaseChannelInput+".url") {
				return strings.TrimSpace(line)
			}
		}
	}
	return "flake-file.inputs.nixpkgs.url = \"<flake url>\";"
}

// checkMachineFile fails when the machine.nix at path holds any static or
// dynamic path literal. Such a path resolves against the staged copy, not the
// host folder, and an imports list there would bypass modules.nix.
func checkMachineFile(path string) error {
	static, err := nixsrc.Paths(path)
	if err != nil {
		return err
	}
	dynamic, err := nixsrc.DynamicPaths(path)
	if err != nil {
		return err
	}
	offenders := append(static, dynamic...)
	if len(offenders) == 0 {
		return nil
	}
	return fmt.Errorf("%s holds path literals or imports: %s\n"+
		"paths in machine.nix resolve against the staged copy at /etc/nixos/config/, not the host folder, "+
		"and module selection belongs in modules.nix; add a module with:\n  luxos module enable <name>",
		path, strings.Join(offenders, ", "))
}

// Run performs the full self-heal sequence for host, in the order the bash
// self-heal.sh used: ensure the .gitignore, ensure the global environment file (created from
// the embedded template when missing), sync framework modules,
// validate and protect the host folder (L1-L3), ensure this computer's
// hardware folder and the host's link to it, heal host entrypoints,
// validate module boundaries, adopt /etc/nixos (moving entries luxos does
// not own into the backup directory), materialize staging, generate+install framework/flake-file.nix, detect GPUs and install
// framework/gpu.nix, then flake.nix via flake-file, and framework/configuration.nix.
// prune, when true, removes unresolvable import lines from the active
// host's entrypoint instead of erroring.
func Run(w io.Writer, p paths.Paths, host string, prune bool) error {
	hostDir := filepath.Join(p.Machines, host)

	// 1. gitignore
	fmt.Fprintln(w, "Ensuring .gitignore...")
	added, err := gitignore.Ensure(filepath.Join(p.Config, ".gitignore"), gitignoreLines)
	if err != nil {
		return err
	}
	for _, line := range added {
		fmt.Fprintf(w, "  added: %s\n", line)
	}

	// 1b. environment file
	fmt.Fprintln(w, "Ensuring environment file...")
	tmpl, err := framework.File(environmentTemplate)
	if err != nil {
		return err
	}
	envPath := filepath.Join(p.Config, environmentFile)
	created, err := userfile.Create(envPath, tmpl)
	if err != nil {
		return err
	}
	if created {
		fmt.Fprintf(w, "  created: %s\n", envPath)
	}

	// 2. framework modules sync
	fmt.Fprintln(w, "Syncing framework modules...")
	changes, err := framework.Sync(filepath.Join(p.Modules, "system"))
	if err != nil {
		return err
	}
	for _, c := range changes {
		line := fmt.Sprintf("%s: %s", c.Action, c.Path)
		if c.Action == framework.ActionCreated {
			fmt.Fprintln(w, line)
		} else {
			fmt.Fprintln(w, "Warning: "+line)
		}
	}

	// 2b. machine.nix from the template when missing
	if err := ensureMachineFile(w, hostDir); err != nil {
		return err
	}

	// 3. validate and protect the host folder
	fmt.Fprintf(w, "Validating %s...\n", hostDir)
	if err := config.ValidateHost(hostDir); err != nil {
		return err
	}
	protected, err := config.ProtectHost(hostDir)
	if err != nil {
		return err
	}
	if protected {
		fmt.Fprintf(w, "  protected: %s\n", filepath.Join(hostDir, ".plsdonttouch.nix"))
	}

	// 3b. this computer's hardware folder, then the link to it
	hwDir, err := ensureHardware(w, p)
	if err != nil {
		return err
	}
	key := filepath.Base(hwDir)
	fmt.Fprintf(w, "Ensuring local/modules/hardware-support -> .local/hardware/%s link...\n", key)
	if err := links.EnsureHardwareLink(p.Machines, p.HardwareRoot, host, key); err != nil {
		return err
	}

	// 4. ensure modules mirror
	fmt.Fprintf(w, "Ensuring %s's modules mirror...\n", host)
	if err := links.EnsureMirror(p.Machines, p.Modules, host); err != nil {
		return err
	}

	// 4b. ensure modules/local -> .local/machines/<host>/modules link
	fmt.Fprintf(w, "Ensuring modules/local -> .local/machines/%s/modules link...\n", host)
	if err := links.EnsureLocalModules(p.Machines, p.Modules, host); err != nil {
		return err
	}

	// 5. heal imports
	fmt.Fprintln(w, "Healing modules imports...")
	healChanges, healWarnings, err := imports.Heal(p.Machines, p.Modules, host, prune)
	for _, c := range healChanges {
		fmt.Fprintln(w, formatImportChange(c))
	}
	for _, wm := range healWarnings {
		fmt.Fprintln(w, "Warning: "+wm)
	}
	if err != nil {
		return err
	}

	// 6. validate module boundaries
	fmt.Fprintln(w, "Validating module boundaries...")
	us, err := units.Walk(p.Modules, filepath.Join(hostDir, "modules"))
	if err != nil {
		return err
	}
	selection, err := imports.List(filepath.Join(hostDir, selectionFile))
	if err != nil {
		return err
	}
	violations, err := refs.Validate(p.Modules, us, selection)
	if err != nil {
		return err
	}
	if len(violations) > 0 {
		for _, v := range violations {
			fmt.Fprintf(w, "Error: %s: %s\n", v.File, v.Message)
		}
		return fmt.Errorf("module boundary violations: %d", len(violations))
	}

	// 6b. machine.nix may hold no path literals and no imports
	if err := checkMachineFile(filepath.Join(hostDir, config.MachineFile)); err != nil {
		return err
	}

	// 6c. the base channel is declared in machine.nix
	nixpkgsURL, err := readBaseChannel(filepath.Join(hostDir, config.MachineFile))
	if err != nil {
		return err
	}

	// 7. ensure local link
	fmt.Fprintf(w, "Ensuring local -> .local/machines/%s link...\n", host)
	if err := links.EnsureLocalLink(p.Config, p.Machines, host); err != nil {
		return err
	}

	// 7a. adopt the flake root: move strangers out of it
	fmt.Fprintf(w, "Adopting %s...\n", p.Staging)
	adoptChanges, err := staging.Adopt(p.Staging, p.Backup)
	if errors.Is(err, staging.ErrNoBackupDir) {
		return fmt.Errorf("%s holds entries luxos does not own and there is no user to move them to; choose a directory with:\n  luxos rebuild --backup-dir <path>", p.Staging)
	}
	if err != nil {
		return err
	}
	for _, c := range adoptChanges {
		if c.Kind == staging.ChangeMoved {
			fmt.Fprintf(w, "  moved: %s -> %s\n", c.Path, c.Dest)
		} else {
			fmt.Fprintf(w, "  converted %s from a symlink to a real directory\n", c.Path)
		}
	}

	// 8. materialize staging
	fmt.Fprintf(w, "Materializing %s for %s...\n", p.Staging, host)
	if err := staging.Materialize(p.Staging, p.Modules, hostDir, us, filepath.Join(hostDir, "flake.lock"), envPath, nixpkgsURL); err != nil {
		return err
	}

	// 9. generate framework/flake-file.nix, let flake-file write flake.nix, lock
	fmt.Fprintln(w, "Generating flake.nix with flake-file...")
	bootstrap, err := generate.FlakeBootstrap(host)
	if err != nil {
		return err
	}
	if err := staging.Install(p.Staging, "framework/flake-file.nix", bootstrap); err != nil {
		return err
	}

	// 9b. detect GPUs and install the fact file
	fmt.Fprintln(w, "Detecting GPUs...")
	gpus, err := computer.DetectGPUs(p.Sys)
	if err != nil {
		return err
	}
	for _, g := range gpus {
		fmt.Fprintf(w, "  %s %s: %s\n", g.Vendor, g.Class, g.BusID)
	}
	gpuContent, err := computer.RenderGPUs(gpus)
	if err != nil {
		return err
	}
	if err := staging.Install(p.Staging, "framework/gpu.nix", gpuContent); err != nil {
		return err
	}

	if err := writeFlake(p.Staging); err != nil {
		return err
	}
	if err := flakeLock(p.Staging); err != nil {
		return err
	}
	hostLock := filepath.Join(hostDir, "flake.lock")
	changed, err := staging.LockChanged(p.Staging, hostLock)
	if err != nil {
		return err
	}
	if changed {
		if err := staging.CopyLockBack(p.Staging, hostLock); err != nil {
			return err
		}
		fmt.Fprintf(w, "  locked new inputs: %s\n", hostLock)
	}

	// 10. generate and install framework/configuration.nix
	fmt.Fprintln(w, "Generating configuration.nix...")
	configContent, err := generate.Configuration(host)
	if err != nil {
		return err
	}
	if err := staging.Install(p.Staging, "framework/configuration.nix", configContent); err != nil {
		return err
	}

	// 11. make the generated tree read-only
	fmt.Fprintf(w, "Sealing %s...\n", p.Staging)
	return staging.Seal(p.Staging)
}

// formatImportChange renders one imports.Change the way bash's
// imports::retarget printed it: "<file>: ./<old> -> ./<new>", or
// "<file>: removed ./<old>" when New is empty.
func formatImportChange(c imports.Change) string {
	if c.New == "" {
		return fmt.Sprintf("%s: removed ./%s", c.File, c.Old)
	}
	return fmt.Sprintf("%s: ./%s -> ./%s", c.File, c.Old, c.New)
}
