package config

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/DeprecatedLuar/luxos/internal/hardware"
	"github.com/DeprecatedLuar/luxos/internal/nix"
	"github.com/DeprecatedLuar/luxos/internal/paths"
	"github.com/DeprecatedLuar/luxos/internal/templates"
	"github.com/DeprecatedLuar/luxos/internal/ui"
)

// Exported so callers name them without repeating the strings.
const (
	DefaultFile        = "default.nix"
	HardwareConfigFile = "hardware-configuration.nix"
	BootFile           = "boot.nix"
	HardwareFile       = "hardware.nix"

	HardwareUnitName = "hardware-support"
	HardwareUnitPath = "local/" + HardwareUnitName

	hardwareTemplate        = "starters/hardware.nix"
	hardwareDefaultTemplate = "starters/hardware-default.nix"

	hardwareConfigNote = " (generated by nixos-generate-config; luxos never rewrites it)"
	bootNote           = " (review it; luxos never rewrites it)"

	// missingHardwareLink is the error when no rebuild has linked this computer's hardware folder.
	missingHardwareLink = "For some reason the hardware-support link is missing. You need that to proceed so run 'luxos rebuild build' real quick"
)

// HardwareDir returns this computer's hardware folder, keyed by its product_uuid.
func HardwareDir(sysDir, hardwareRoot string) (string, error) {
	key, err := hardware.Key(sysDir)
	if err != nil {
		return "", err
	}
	return filepath.Join(hardwareRoot, key), nil
}

// LinkedHardwareDir returns this computer's hardware folder as rebuild
// recorded it: the active host's hardware-support link, read through
// modules/local. It needs no root.
func LinkedHardwareDir(modulesDir string) (string, error) {
	dir, err := filepath.EvalSymlinks(filepath.Join(modulesDir, localLinkName, HardwareUnitName))
	if errors.Is(err, fs.ErrNotExist) {
		return "", errors.New(missingHardwareLink)
	}
	if err != nil {
		return "", err
	}
	return dir, nil
}

// EnsureHardware creates this computer's hardware folder and whichever of its
// files are missing, then validates it. Existing files are never rewritten.
func EnsureHardware(out *ui.Progress, p paths.Paths) (string, error) {
	hwDir, err := HardwareDir(p.Sys, p.HardwareRoot)
	if err != nil {
		return "", err
	}
	out.Printf("Ensuring %s...\n", hwDir)
	if err := MkdirAll(hwDir); err != nil {
		return "", err
	}

	hwConfig := filepath.Join(hwDir, HardwareConfigFile)
	created, err := ensureHardwareConfig(hwConfig)
	if err != nil {
		return "", err
	}
	if created {
		out.Changef("  created: %s%s", hwConfig, hardwareConfigNote)
	}

	bootPath := filepath.Join(hwDir, BootFile)
	created, err = ensureBoot(bootPath, p.Sys, p.Mounts)
	if err != nil {
		return "", err
	}
	if created {
		out.Changef("  created: %s%s", bootPath, bootNote)
	}

	for _, f := range []struct{ name, template string }{
		{HardwareFile, hardwareTemplate},
		{DefaultFile, hardwareDefaultTemplate},
	} {
		tmpl, err := templates.File(f.template)
		if err != nil {
			return "", err
		}
		path := filepath.Join(hwDir, f.name)
		created, err = CreateFile(path, tmpl)
		if err != nil {
			return "", err
		}
		if created {
			out.Changef("  created: %s", path)
		}
	}

	if err := ValidateHardware(hwDir); err != nil {
		return "", err
	}
	return hwDir, out.Err()
}

// ensureHardwareConfig writes hardwareFile from nixos-generate-config when
// nothing exists at that path, and reports whether it did. An existing entry
// is never read or rewritten.
func ensureHardwareConfig(hardwareFile string) (created bool, err error) {
	if _, err := os.Lstat(hardwareFile); err == nil {
		return false, nil
	} else if !errors.Is(err, fs.ErrNotExist) {
		return false, err
	}
	content, err := nix.ShowHardwareConfig()
	if err != nil {
		return false, fmt.Errorf("cannot generate %s: %w\nrun by hand: nixos-generate-config --show-hardware-config > %s", hardwareFile, err, hardwareFile)
	}
	if err := WriteFile(hardwareFile, content); err != nil {
		return false, fmt.Errorf("config.ensureHardwareConfig: write %s: %w", hardwareFile, err)
	}
	return true, nil
}

// ensureBoot writes bootFile from boot loader detection when nothing exists
// at that path, and reports whether it did. An existing entry of any kind is
// left alone. A detection failure is a hard error naming bootFile.
func ensureBoot(bootFile, sysDir, mountsFile string) (created bool, err error) {
	if _, err := os.Lstat(bootFile); err == nil {
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("config.ensureBoot: stat %s: %w", bootFile, err)
	}

	loader, err := hardware.DetectBoot(sysDir, mountsFile)
	if err != nil {
		return false, fmt.Errorf("cannot detect the boot loader: %s\nwrite %s by hand to configure the boot loader", err, bootFile)
	}

	content, err := hardware.RenderBoot(loader)
	if err != nil {
		return false, err
	}

	if err := WriteFile(bootFile, content); err != nil {
		return false, fmt.Errorf("config.ensureBoot: write %s: %w", bootFile, err)
	}

	return true, nil
}

// Any other entry is allowed. Every problem is reported, sorted, in one error
// shaped like ValidateHost's: "missing <name>" or "<name> is not a regular file".
func ValidateHardware(dir string) error {
	var problems []string
	for _, name := range []string{DefaultFile, HardwareConfigFile, BootFile, HardwareFile} {
		info, err := os.Stat(filepath.Join(dir, name))
		switch {
		case os.IsNotExist(err):
			problems = append(problems, "missing "+name)
		case err != nil || !info.Mode().IsRegular():
			problems = append(problems, name+" is not a regular file")
		}
	}
	return problemsError("invalid hardware folder "+dir, problems)
}
