#!/usr/bin/env bash
set -euo pipefail

# Generates configuration.nix from a machine's machine.toml and flake.nix from
# CONFIG_DIR/channels.toml, and discovers the shared kind pools (modules,
# services, users, ...) at CONFIG_DIR root that every machine reads from.
# Callers must source internal/env.sh (FRAMEWORK_DIR, CONFIG_DIR, LOCAL_DIR)
# first.
#
# Every function here aborts the process (exit 1) on error rather than
# returning non-zero — callers do not check return codes.

# Hand-edited declaration of the flake's inputs, at CONFIG_DIR root.
CONFIGGEN_CHANNELS_FILE="channels.toml"

# The platform every generated flake builds for.
CONFIGGEN_NIX_SYSTEM="x86_64-linux"

# system.nix references inputs.nixpkgs (nix.registry, nix.nixPath), so the
# base channel is always emitted under this input name — its declared name
# only ever appears in the overlay.
CONFIGGEN_BASE_INPUT_NAME="nixpkgs"

# Names the generator emits itself; a channel/flake may not claim them.
CONFIGGEN_RESERVED_NAMES=("self" "$CONFIGGEN_BASE_INPUT_NAME")

# A channel/flake name becomes a Nix attribute and a flake input name.
CONFIGGEN_NAME_REGEX='^[a-zA-Z_][a-zA-Z0-9_-]*$'

# Generated paths at CONFIG_DIR root, ignored by the generated root
# .gitignore. flake.nix and configuration.nix are written straight into
# $STAGING_DIR (see configgen::generate/generate_flake) and never land in
# CONFIG_DIR at all. Derived from configgen::discover_kinds rather than
# hand-maintained: each kind's own entrypoint default.nix is a generated
# symlink (see links::ensure_mirror), modules/system is the framework pool
# symlink (see links::ensure_framework_pool), and every .local/<host>'s own
# default.nix is generated by configgen::generate_default.
CONFIGGEN_GITIGNORE_FILE=".gitignore"
configgen::ignored_paths() {
    local kind
    for kind in $(configgen::discover_kinds); do
        echo "/$kind/default.nix"
    done
    echo "/modules/system"
    echo "/.local/*/default.nix"
}

#──[Discovery]──────────────────────────────────────────────────────────────

# The shared kind pools at CONFIG_DIR root — one directory per kind
# (modules, services, users, ...), excluding .local (the per-host mirror,
# never itself a kind). The single source every derived list below is built
# from: adding a directory here is the only step needed to add a kind.
configgen::discover_kinds() {
    local entry
    for entry in "$CONFIG_DIR"/*/; do
        [[ -d "$entry" ]] || continue
        [[ "$(basename "$entry")" == "$(basename "$LOCAL_DIR")" ]] && continue
        basename "$entry"
    done | LC_ALL=C sort
}

# List machine names — one per directory under $LOCAL_DIR containing a
# machine.toml. This is the authoritative machine list; flake.nix's
# nixosConfigurations is generated from it, so adding a machine is only ever
# adding a directory under $LOCAL_DIR.
configgen::discover_machines() {
    local entry
    for entry in "$LOCAL_DIR"/*/; do
        [[ -f "${entry}machine.toml" ]] || continue
        basename "$entry"
    done | LC_ALL=C sort
}

# Resolve a machine name to its directory under $LOCAL_DIR. Hard error naming
# the path tried if it doesn't hold a machine.toml — the caller never has to
# check itself.
configgen::resolve_machine() {
    local name="$1"
    local dir="$LOCAL_DIR/$name"
    if [[ ! -f "$dir/machine.toml" ]]; then
        echo "Error: no machine.toml under $dir" >&2
        exit 1
    fi
    echo "$dir"
}

#──[TOML parsing]───────────────────────────────────────────────────────────
# Private helpers — only configgen.sh itself calls these.

# Parse TOML string value (key = "value")
parse_string() {
    local file=$1
    local key=$2
    grep -E "^${key}[[:space:]]*=" "$file" | sed 's/.*= *"\(.*\)".*/\1/' | head -1
}

# Parse TOML array (key = ["a", "b", "c"])
parse_array() {
    local file=$1
    local key=$2
    grep -E "^${key}[[:space:]]*=" "$file" | sed 's/.*= *\[\(.*\)\].*/\1/' | tr ',' '\n' | sed 's/^[" \t]*//; s/[" \t]*$//' | grep -v '^$' || true
}

# Emit "key<TAB>value" for every key belonging to [section] in a TOML file.
# An empty section name selects top-level keys — the ones before the first
# header. Blank lines and comments are skipped, inline comments and the
# surrounding quotes of a string value are stripped.
#
# Deliberately separate from parse_string/parse_array above: those are
# column-0-anchored greps with no concept of a header, so they can't see an
# indented key and can't tell two sections apart. They stay machine.toml's.
_configgen_parse_section() {
    local file="$1"
    local want="$2"
    awk -v want="$want" -v file="$file" '
        { sub(/\r$/, "") }
        /^[[:space:]]*#/ { next }
        /^[[:space:]]*$/ { next }
        /^[[:space:]]*\[/ {
            section = $0
            sub(/^[[:space:]]*\[[[:space:]]*/, "", section)
            sub(/[[:space:]]*\].*$/, "", section)
            current = section
            next
        }
        {
            eq = index($0, "=")
            if (eq == 0) {
                printf "Error: %s:%d is neither a header nor a key = value\n", file, NR > "/dev/stderr"
                exit 1
            }
            key = substr($0, 1, eq - 1)
            val = substr($0, eq + 1)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
            sub(/^[[:space:]]+/, "", val)
            if (substr(val, 1, 1) == "\"") {
                close_at = index(substr(val, 2), "\"")
                if (close_at == 0) {
                    printf "Error: %s:%d has an unterminated quoted value\n", file, NR > "/dev/stderr"
                    exit 1
                }
                val = substr(val, 2, close_at - 1)
            } else {
                sub(/#.*$/, "", val)
                sub(/[[:space:]]+$/, "", val)
            }
            if (current == want) print key "\t" val
        }
    ' "$file"
}

# Validate TOML file structure. "Required" and "allowed" are kept separate on
# purpose: a missing required key is a hard error, but an unknown key only
# warns — it might be a newly added optional key the parser doesn't know
# about yet, and hard-erroring on it would actively block schema changes.
validate_toml() {
    local file=$1
    local required_keys=("hostName" "timeZone" "locale" "stateVersion" "users")
    # Extend here as optional keys are added to machine.toml's schema.
    local allowed_keys=("${required_keys[@]}")
    local errors=()

    # Check for required keys, anchored so e.g. "hostName" doesn't also match
    # a hypothetical "hostNameExtra".
    local key
    for key in "${required_keys[@]}"; do
        if ! grep -qE "^${key}[[:space:]]*=" "$file"; then
            errors+=("Missing required key: $key")
        fi
    done

    # Warn on unexpected keys (non-comment, non-empty lines). Column-0
    # anchored like the rest of machine.toml's parsing, so an indented or
    # continuation line is skipped rather than misread as a new key.
    local line
    while IFS= read -r line; do
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ "$line" =~ ^[[:space:]]*$ ]] && continue
        [[ "$line" =~ ^([a-zA-Z_][a-zA-Z0-9_]*)[[:space:]]*= ]] || continue

        key="${BASH_REMATCH[1]}"
        if [[ ! " ${allowed_keys[*]} " =~ " $key " ]]; then
            echo "Warning: unknown key '$key' in $file" >&2
        fi
    done < "$file"

    # Report errors
    if [[ ${#errors[@]} -gt 0 ]]; then
        echo "Error: Invalid TOML format in $file"
        printf '  - %s\n' "${errors[@]}"
        exit 1
    fi
}

# Generate a machine.toml template holding exactly the keys it owns: users
# and the scalars. modules/services selection now lives in each host's own
# hand-written entrypoints (.local/<host>/{modules,services}/default.nix),
# not in machine.toml, so no discovered-options comment block is emitted here.
_configgen_generate_template() {
    local machine_dir="$1" output="$2"

    cat > "$output" << 'EOF'
# NixOS Machine Configuration
# Auto-generated template - edit as needed

# Users to import (first user is main user)
users = []
hostName = "hostname"
timeZone = "America/Sao_Paulo"
locale = "en_US.UTF-8"
stateVersion = "25.05"
EOF
}

#──[Generation]─────────────────────────────────────────────────────────────

# Shared "Auto-generated - DO NOT EDIT" banner for every generated file.
# $2 names the file/action to re-run in the third line's instruction.
_configgen_header() {
    local source_desc="$1" instruction="$2"
    cat << EOF
# Auto-generated from $source_desc - DO NOT EDIT
# $instruction
EOF
}

# Generate configuration.nix from a machine directory's machine.toml, to
# $output_file. Written by the caller into $STAGING_DIR — the imports below
# are relative to there (./framework, ./config), not to $machine_dir, so this
# file cannot be evaluated anywhere else.
configgen::generate() {
    local machine_dir="${1:-.}" output_file="$2"
    local machine_toml="$machine_dir/machine.toml"

    # Check if machine.toml exists, create from template if not
    if [[ ! -f "$machine_toml" ]]; then
        echo "Creating $machine_toml from template..."
        _configgen_generate_template "$machine_dir" "$machine_toml"
        echo "✓ Created template with auto-discovered modules and users"
        exit 1
    fi

    # Validate TOML structure
    validate_toml "$machine_toml"

    # Parse variables
    local host_name time_zone locale state_version main_user
    host_name=$(parse_string "$machine_toml" hostName)
    time_zone=$(parse_string "$machine_toml" timeZone)
    locale=$(parse_string "$machine_toml" locale)
    state_version=$(parse_string "$machine_toml" stateVersion)

    # Derive main user from first user in array
    main_user=$(parse_array "$machine_toml" users | head -1)

    # Validate required fields
    if [[ -z "$main_user" ]]; then
        echo "Error: users array must have at least one user in $machine_toml"
        exit 1
    fi

    if [[ -z "$host_name" ]]; then
        echo "Error: hostName is required in $machine_toml"
        exit 1
    fi

    if [[ -z "$state_version" ]]; then
        echo "Error: stateVersion is required in $machine_toml"
        exit 1
    fi

    # No name resolution here: every machine imports the same things,
    # relative to $STAGING_DIR where this file is written — one entry per
    # discovered kind (each kind's own default.nix, real by the time this is
    # staged: modules/services are the host's hand-written entrypoint,
    # users is generated by configgen::generate_folder_default), plus the
    # fixed framework and per-host local entries.
    local -a machine_imports=("./framework/system.nix")
    local kind
    for kind in $(configgen::discover_kinds); do
        machine_imports+=("./config/$kind")
    done
    machine_imports+=("./config/local")

    local imports_block
    imports_block=$(printf '    %s\n' "${machine_imports[@]}")

    mkdir -p "$(dirname "$output_file")"
    { _configgen_header "machine.toml" \
        "Edit machine.toml instead and run: sudo nixos-rebuild switch"
      echo "# Written by self-heal into \$STAGING_DIR — its imports below only resolve there."
      cat << EOF

{ ... }:

let
  mainUser = "$main_user";
  hostName = "$host_name";
in
{
  time.timeZone = "$time_zone";
  i18n.defaultLocale = "$locale";
  system.stateVersion = "$state_version";

  imports = [
$imports_block
  ];

  networking.hostName = hostName;
  _module.args = { inherit mainUser hostName; };
}
EOF
    } > "$output_file"

    echo "✓ Generated: $output_file"
}

# Generate <machine_dir>/<kind>/default.nix, importing exactly [names...],
# each resolved against the SHARED pool at $CONFIG_DIR/<kind> — flat at the
# point of selection, so name -> path is ./<name>.nix when that file exists,
# else ./<name> (a directory carrying its own default.nix). The written
# default.nix is symlinked into the pool by links::ensure_mirror, so these
# relative import paths resolve against the pool directory, not machine_dir
# (verified: a relative path inside a symlinked default.nix resolves against
# the symlink's own directory). No names means no imports.
#
# Now used only for users — modules/services selection moved to each host's
# own hand-written entrypoint (.local/<host>/{modules,services}/default.nix).
configgen::generate_folder_default() {
    local machine_dir="$1" kind="$2"
    shift 2
    local names=("$@")
    local pool_dir="$CONFIG_DIR/$kind"
    local output_file="$machine_dir/$kind/default.nix"

    local imports=()
    local name path
    for name in ${names[@]+"${names[@]}"}; do
        [[ -n "$name" ]] || continue
        if [[ -f "$pool_dir/$name.nix" ]]; then
            path="$name.nix"
        elif [[ -f "$pool_dir/$name/default.nix" ]]; then
            path="$name"
        else
            echo "Error: $kind '$name' not found under $pool_dir" >&2
            exit 1
        fi
        imports+=("    ./$path")
    done

    mkdir -p "$(dirname "$output_file")"

    local imports_block=""
    [[ ${#imports[@]} -gt 0 ]] && imports_block=$'\n'$(printf '%s\n' "${imports[@]}")$'\n  '

    { _configgen_header "machine.toml" \
        "Generated by self-heal from machine.toml's users array. Edit machine.toml and run: sudo nixos-rebuild switch"
      cat << EOF

{ ... }:

{
  imports = [${imports_block}];
}
EOF
    } > "$output_file"

    echo "✓ Generated: $output_file"
}

# Generate <machine_dir>/default.nix — the .local/<host> entrypoint — in
# discovery mode: every plain .nix file at machine_dir's root, plus any
# root-level directory carrying its own default.nix, gets imported.
# machine.toml is skipped (not a Nix file to import), and so is any name
# matching a discovered root kind (modules, services, users, ...): each of
# those already has its own default.nix, wired in directly by
# configgen::generate via ./config/<kind> — importing it again here would
# double every module/service/user.
configgen::generate_default() {
    local machine_dir="${1:-.}"
    local output_file="$machine_dir/default.nix"

    local -a kind_names
    mapfile -t kind_names < <(configgen::discover_kinds)

    local -a imports=()
    local entry base skip k
    for entry in "$machine_dir"/*; do
        [[ -e "$entry" ]] || continue
        base=$(basename "$entry")
        [[ "$base" == "machine.toml" || "$base" == "default.nix" ]] && continue

        if [[ -d "$entry" ]]; then
            skip=false
            for k in ${kind_names[@]+"${kind_names[@]}"}; do
                [[ "$base" == "$k" ]] && { skip=true; break; }
            done
            $skip && continue
            [[ -f "$entry/default.nix" ]] || continue
            imports+=("    ./$base")
        elif [[ "$entry" == *.nix ]]; then
            imports+=("    ./$base")
        fi
    done

    mkdir -p "$machine_dir"

    local imports_block=""
    if [[ ${#imports[@]} -gt 0 ]]; then
        imports_block=$'\n'$(printf '%s\n' "${imports[@]}" | LC_ALL=C sort)$'\n  '
    fi

    { _configgen_header "this directory's contents" \
        "Generated by self-heal from whatever is present here (excluding kind mirrors and machine.toml). Drop/remove files here and run: sudo nixos-rebuild switch"
      cat << EOF

{ ... }:

{
  imports = [${imports_block}];
}
EOF
    } > "$output_file"

    echo "✓ Generated: $output_file"
}

#──[Flake generation]───────────────────────────────────────────────────────

# Reject a channel/flake name that can't be a flake input or an overlay attr.
_configgen_validate_name() {
    local name="$1"
    local file="$2"
    local reserved

    if [[ ! "$name" =~ $CONFIGGEN_NAME_REGEX ]]; then
        echo "Error: '$name' in $file is not a valid Nix identifier" >&2
        echo "  Names must match $CONFIGGEN_NAME_REGEX" >&2
        exit 1
    fi

    for reserved in "${CONFIGGEN_RESERVED_NAMES[@]}"; do
        if [[ "$name" == "$reserved" ]]; then
            echo "Error: '$name' in $file is reserved — the generator emits it itself" >&2
            exit 1
        fi
    done
}

# Warn when flake.lock's inputs no longer match the ones just generated.
# Renaming a channel orphans its lock entry and silently re-resolves that
# input to whatever HEAD is today, which is otherwise invisible.
_configgen_warn_lock_drift() {
    local lock="$CONFIG_DIR/flake.lock"
    [[ -f "$lock" ]] || return 0

    if ! command -v jq >/dev/null 2>&1; then
        echo "Error: jq not found — cannot check $lock for drift" >&2
        echo "  jq is a framework dependency (see system.nix); reinstall it or use --bypass." >&2
        exit 1
    fi

    local locked generated name
    locked=$(jq -r '.nodes.root.inputs | keys[]' "$lock" | LC_ALL=C sort)
    generated=$(printf '%s\n' "$@" | LC_ALL=C sort)
    [[ "$locked" == "$generated" ]] && return 0

    echo "Warning: $lock no longer matches $CONFIGGEN_CHANNELS_FILE" >&2
    while IFS= read -r name; do
        [[ -n "$name" ]] && echo "  orphaned in flake.lock: $name" >&2
    done < <(comm -23 <(echo "$locked") <(echo "$generated"))
    while IFS= read -r name; do
        [[ -n "$name" ]] && echo "  unlocked, will resolve to HEAD: $name" >&2
    done < <(comm -13 <(echo "$locked") <(echo "$generated"))
    echo "  Run 'nixos-rebuild --update-lock' to re-lock deliberately." >&2
}

# Generate flake.nix at $output_file from CONFIG_DIR/channels.toml, for the
# one machine being staged. Every declared nixpkgs channel becomes both a
# flake input and an overlay attribute, so a package reference always states
# its origin (stable.rofi, unstable.hyprland). Everything is emitted in
# LC_ALL=C sorted order, so a rerun with no source change is byte-identical.
#
# Written to $STAGING_DIR, never to CONFIG_DIR: its own ./configuration.nix
# import only exists there. One nixosConfigurations entry, not one per
# machine, for the same reason — staging::materialize copies the active
# machine alone (as ./config, unions dereferenced), so ./configuration.nix
# at the flake root describes that machine and nothing else. Enumerating
# every machine here would point every attribute at the same file —
# nixosConfigurations.nuremberg would build paraloid.
configgen::generate_flake() {
    local host_name="$1" output_file="$2"
    local channels_toml="$CONFIG_DIR/$CONFIGGEN_CHANNELS_FILE"

    if [[ -z "$host_name" ]]; then
        echo "Error: configgen::generate_flake requires the machine name" >&2
        exit 1
    fi

    if [[ ! -f "$channels_toml" ]]; then
        echo "Error: $channels_toml not found — run 'setup' to scaffold it" >&2
        exit 1
    fi

    local toplevel channels_raw flakes_raw
    toplevel=$(_configgen_parse_section "$channels_toml" "")
    channels_raw=$(_configgen_parse_section "$channels_toml" channels | LC_ALL=C sort)
    flakes_raw=$(_configgen_parse_section "$channels_toml" flakes | LC_ALL=C sort)

    local key value
    local base=""
    while IFS=$'\t' read -r key value; do
        case "$key" in
            "") ;;
            base) base="$value" ;;
            *)
                echo "Error: unknown top-level key '$key' in $channels_toml" >&2
                exit 1
                ;;
        esac
    done <<< "$toplevel"

    if [[ -z "$base" ]]; then
        echo "Error: 'base' is required in $channels_toml" >&2
        echo "  It names the channel that builds the system (provides lib)." >&2
        exit 1
    fi

    local channel_names=() channel_urls=()
    while IFS=$'\t' read -r key value; do
        [[ -n "$key" ]] || continue
        _configgen_validate_name "$key" "$channels_toml"
        channel_names+=("$key")
        channel_urls+=("$value")
    done <<< "$channels_raw"

    local flake_names=() flake_urls=()
    while IFS=$'\t' read -r key value; do
        [[ -n "$key" ]] || continue
        _configgen_validate_name "$key" "$channels_toml"
        flake_names+=("$key")
        flake_urls+=("$value")
    done <<< "$flakes_raw"

    if [[ ${#channel_names[@]} -eq 0 ]]; then
        echo "Error: $channels_toml declares no [channels] entry" >&2
        exit 1
    fi

    local duplicate
    duplicate=$(printf '%s\n' "${channel_names[@]}" ${flake_names[@]+"${flake_names[@]}"} \
        | LC_ALL=C sort | uniq -d)
    if [[ -n "$duplicate" ]]; then
        echo "Error: name declared more than once in $channels_toml:" >&2
        printf '  - %s\n' $duplicate >&2
        exit 1
    fi

    if ! printf '%s\n' "${channel_names[@]}" | grep -qxF "$base"; then
        echo "Error: base = \"$base\" is not a declared [channels] entry in $channels_toml" >&2
        exit 1
    fi

    # Base channel first, then the rest in sorted order — the base is the one
    # asymmetric entry (it owns the nixpkgs input name and aliases prev).
    local inputs_block="" overlay_block="" outputs_args="self, $CONFIGGEN_BASE_INPUT_NAME"
    local lock_inputs=("$CONFIGGEN_BASE_INPUT_NAME")
    local i name url
    for i in "${!channel_names[@]}"; do
        [[ "${channel_names[$i]}" == "$base" ]] || continue
        inputs_block+="    $CONFIGGEN_BASE_INPUT_NAME.url = \"${channel_urls[$i]}\";  # base channel: $base"$'\n'
        overlay_block+="      $base = prev;"$'\n'
    done
    for i in "${!channel_names[@]}"; do
        name="${channel_names[$i]}"
        url="${channel_urls[$i]}"
        [[ "$name" != "$base" ]] || continue
        inputs_block+="    $name.url = \"$url\";"$'\n'
        overlay_block+="      $name = import $name { inherit (prev.stdenv.hostPlatform) system; inherit (prev) config; };"$'\n'
        outputs_args+=", $name"
        lock_inputs+=("$name")
    done
    for i in ${flake_names[@]+"${!flake_names[@]}"}; do
        inputs_block+="    ${flake_names[$i]}.url = \"${flake_urls[$i]}\";"$'\n'
        lock_inputs+=("${flake_names[$i]}")
    done

    inputs_block="${inputs_block%$'\n'}"
    overlay_block="${overlay_block%$'\n'}"

    mkdir -p "$(dirname "$output_file")"
    { _configgen_header "$CONFIGGEN_CHANNELS_FILE" \
        "Edit $CONFIGGEN_CHANNELS_FILE and run: sudo nixos-rebuild switch"
      cat << EOF

{
  description = "luxos machine configurations";

  inputs = {
$inputs_block
  };

  outputs = { $outputs_args, ... }@inputs:
  let
    system = "$CONFIGGEN_NIX_SYSTEM";

    # Exposes every declared channel as pkgs.<channel>.<package>, so a package
    # reference always states which channel it came from. The base channel
    # aliases prev instead of re-importing itself (pkgs already is that
    # channel); the others inherit config so allowUnfree and friends carry
    # over rather than being restated here.
    channelOverlay = final: prev: {
$overlay_block
    };

    # Machine modules reach the framework's through the union
    # (modules/system -> \$FRAMEWORK_DIR/modules, dereferenced by staging),
    # so no specialArg carries a framework path across the repo boundary.
    mkHost = hostName: $CONFIGGEN_BASE_INPUT_NAME.lib.nixosSystem {
      inherit system;
      specialArgs = { inherit inputs hostName; };
      modules = [
        ./configuration.nix
        { nixpkgs.overlays = [ channelOverlay ]; }
      ];
    };
  in {
    # The staged flake root holds exactly one machine's configuration.nix, so
    # it exposes exactly one host. Regenerated per machine on every run.
    nixosConfigurations.$host_name = mkHost "$host_name";
  };
}
EOF
    } > "$output_file"

    _configgen_warn_lock_drift "${lock_inputs[@]}"

    echo "✓ Generated: $output_file"
}

# Generate CONFIG_DIR's root .gitignore. The generator is the only thing that
# knows what it generates, so it declares that itself rather than leaving a
# hand-maintained list to drift out of sync with it.
configgen::generate_root_gitignore() {
    local output_file="$CONFIG_DIR/$CONFIGGEN_GITIGNORE_FILE"

    configgen::ignored_paths > "$output_file"

    echo "✓ Generated: $output_file"
}
